### ISSUE TITLE
Organization of project packages

### ISSUE THREAD

**Issue by mjablecnik** [needle-dart/needle_orm.dart#7]
Hello, I found your `needle_orm` project and looks very nice :-) Maybe I will use it in the future ;-)

I also look into your `needle-dart` organization and I see you have there many small repositories for needle_orm project.
I have only one question: Why don't you create only one needle_orm repository where you will have all these packages?

Many other projects like [Bloc](https://github.com/felangel/bloc), [Jaspr](https://github.com/schultek/jaspr), [Riverpod](https://github.com/rrousselGit/riverpod) and others have more packages in only one single repository. So why not also you? 
I think it is more clear and it can be good for contributors when they will look everything in one place without need to download many repositories..

Thank you for your response :-)

**Comment by outersky** [comment]
Good point, sounds like one single repository will be better. I'll handle this ASAP

**Comment by outersky** [comment]
Done : https://github.com/needle-dart/needle-orm-all.git
